platform :ios, '9.0'
use_frameworks!
target 'LZJ_Coin' do
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.4'
pod 'RxSwift',    '~> 3.0'
pod 'RxCocoa',    '~> 3.0'
pod 'Charts'
pod 'HandyJSON'
pod 'SnapKit', '~> 3.2.0'
pod 'Bugly'
pod 'Kingfisher'
pod 'Then', '~> 2.1'
end

target 'LZJ_ShowCoin'  do
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.4'
pod 'HandyJSON'
pod 'Kingfisher'
end
